apiVersion: v1
kind: Namespace
metadata:
  name: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-server
  name: nfs-server
  namespace: nfs
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        storage: "true"
      containers:
        - image: deejayadi/nfs-server:latest
          imagePullPolicy: IfNotPresent
          name: nfs-server
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
                - SETPCAP
          env:
            - name: SHARED_DIRECTORY
              value: /disk
          ports:
            - containerPort: 111
              name: rpcbind
            - containerPort: 2049
              name: nfs
            - containerPort: 20048
              name: motund
          volumeMounts:
            - mountPath: /disk
              name: disk
      volumes:
        - name: disk
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfs-server
  name: nfs-server
  namespace: nfs
spec:
  selector:
    app: nfs-server
  clusterIP: None
  ports:
    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: TCP
      targetPort: 20048
